[package]
name = "rustlerpdf"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "rustlerpdf"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.26.0"
lopdf = { version = "0.29", features = ["nom_parser"] }
